version: '3.8'
services:
  postgres:
    container_name: batch-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=batch-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
